version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=course
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123123
    ports:
      - "3322:3306"
    networks:
      - LAMP

networks:
  LAMP:
    name: LAMP